### PR TITLE
Finished report-related functionalities

### PR DESCRIPTION
**Pull request by blairyeung**
**The update contains minor bug fixes and error fixes.**
* [+] Now the user are no longer able to register two accounts with the same email, corresponding error messages will be displayed.
* [*] Fixed some errors detected by intellij, for exmaple the `Hashmap` parametrs in the database.
* Fixed some problems in the UI, for exmaple the display of attribuet `reputation` for admin accounts.

### CODE REVIEW

**Review by JY3150 — DISMISSED** [review]
I see that you have fixed some typos in the use cases and controllers. Sorry about writing/approving those codes before carefully read through all of them. But next time please pull request some small changes so that it is really easier to review the codes.

**Comment by HermesCui** [comment]
I saw you fix some typos, and you update a lot of warnings.

**Review by JY3150 — APPROVED** [review]
I have reviewed you added codes, they look fine.

**Review by HermesCui — APPROVED** [review]
Fix some typos and update UI mistakes.

Modify a lot of formal problems

**Pull request merged**
