### PR TITLE
UI and unit tests

### PR DESCRIPTION
**Pull request by JY3150**
In this pull request, we could post a post under the CourseForm and we could comment on a Post under PostForm. Meanwhile, we could see the posts under the course, the comments under the post, by clicking the button of ShowAllPost/showAllComments.

Know the Forum could go back and forth between CousreForm, PostForm, CommentForm, MakeACourse, MakeAPost, MakeAComment.

Adding more presenter in the UI. Decrease the probability of crashing the project by having more try and catch function. Also, get more presenters to show errors.

For the JUnit Test wise, I have added several tests for different reasons why a register may fail. These tests include: Duplicate username, Weak password, Invalid email. I also included a test for successfully register a user and successfully get a user.

### CODE REVIEW

**Review by Teinble — DISMISSED** [review]
I reviewed all parts related to my code. I think they works fine for me. Besides there are some commented codes are not been deleted. I assume those code still has some use.

**Review by wilso16 — APPROVED** [review]
- Make sure to update UI level code in accordance to clean architecture rules violated (UI importing Entities may be troublesome)
-

**Review by blairyeung — CHANGES_REQUESTED** [review]
I think that you shuold remove the commented code blocks for the sake of readability.
I also think you might need to write some comments / java docs for some of the UI.
Otherwise it looks good to me.

**Comment by JY3150** [comment]
> I think that you shuold remove the commented code blocks for the sake of readability. I also think you might need to write some comments / java docs for some of the UI. Otherwise it looks good to me.

I have deleted the commented code in usecases, controllers, and entities. The commented codes in databases and ui/presenters will be handled by you and Will as you guys finish modifying those files.

**Review by blairyeung — CHANGES_REQUESTED** [review]
Can you change the gradle file back to the original one? It seems like it is not passing the gradle checks.

**Comment by JY3150** [comment]
> Can you change the gradle file back to the original one? It seems like it is not passing the gradle checks.

The language level of our project is 16, setting it at 17 will cause some issues when running the code. And adding those Junit tests blocks are essential for running tests. If you meant the github classroom workflow, I have consulted the TA and she said we should not worry about it as it won't affect our grading. But if you are still concerned, I can visit today's office hour and ask the TA there.

**Review by blairyeung — APPROVED** [review]

**Review by Teinble — APPROVED** [review]
I will merge first. I might need the comment code in the UI for debugging. But since changing in UI would not affect the code in the other layer. In the next pull request, I will deal with the comment code in UI.

**Pull request merged**
