### PR TITLE
Final update of ver 1.0

### PR DESCRIPTION
**Pull request by blairyeung**
## Final update of version 1.0
**Curated by Liwei Yang, Xinling Zhao, Tested by Hermes Cui**
We present the project. It gains all the designed functionalities as planed. Here are the updates
### [+] Full functionalities of the report system.
- Users are now able to report the entities `User`, `Course`, `Post`
- These reports are stored in the database through `DatabaseGateway`. The database provides **O(1)** complexity for any operations.
- The reports in the database will be carried out to the administrating team (special `users`) of evaluation and resolution.
- The reports can be **resovled** (or deleted) by the administrator after the problem is resolved.
### [*] Fixing some warning messages
Error messages are fixed to our greatest extend, except some warnings in `DatabaseHandler`, `DatabaseGateway`, due to generalization.
### [+] UI update
- We add one more UI `ReportForm` which is for the administrator to solve all the report which reported by users. It could access from `ProfilePage`, if the `isadmin` attribute of user is true, then there will be a button to be appeared at the bottom. 
- Add more presenting actions for clicking buttons, now the program wouldn't throw Acception and sending error in the terminal. Instead, it will give the porper poping screen to show the error type. 

***All the tests has passed. However, we might be fixing some minor typos/complience with clean architecutre in the next PR.***

image
image
image

### CODE REVIEW

**Review by HermesCui — DISMISSED** [review]
It looks like you fix the big problem at the Report UseCase and the Report Controller.

Besides, this update changes some input type as entities to follow the smell code.

**Review by HermesCui — APPROVED** [review]
Fixed the test and follow the smell code format.

**Review by JY3150 — APPROVED** [review]
This is quite a large pr. It basically fixed all warnings that could be fixed and abstracted the types as much as possible! Nice work. The only flaw was that it was so large and took me a long time to review, it's better to have several smaller prs instead.

**Review by cang-xue — APPROVED** [review]

**Review by JY3150 — APPROVED** [review]
Nice Update. Now this is getting closer to our final goal.

**Review by HermesCui — APPROVED** [review]
Fix some typos .

**Pull request merged**
